name: Test Suits For Database And Routes
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 12345
          POSTGRES_USER: estore
          POSTGRES_DB: estore_test
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        run: npm run test:db
        env:
          TEST_DB_URL: postgres://estore:12345@postgres:5432/estore_test

      - name: Testing Routes
        run: npm run test:routes
        env:
          TEST_DB_URL: postgres://estore:12345@postgres:5432/estore_test
